# Generated by Django 3.1.4 on 2020-12-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'EASY'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10),
        ),
    ]
