# Generated by Django 3.1.4 on 2020-12-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201231_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='owner',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('Medium', 'Medium'), ('Hard', 'Hard'), ('EASY', 'EASY')], max_length=10),
        ),
    ]
